# Generated by Django 2.0 on 2019-11-10 19:32

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ecountry',
            field=django_countries.fields.CountryField(default='India', editable=False, max_length=2),
        ),
        migrations.AddField(
            model_name='employee',
            name='egender',
            field=models.IntegerField(default='male'),
        ),
        migrations.AddField(
            model_name='employee',
            name='eimage',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='employee',
            name='elanguages',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='estate',
            field=models.CharField(default='', editable=False, max_length=10),
        ),
    ]
