# Generated by Django 2.0 on 2019-11-11 08:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20191111_0102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='elanguages',
            new_name='languages',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='ecountry',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='egender',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='estate',
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='econtact',
            field=models.IntegerField(max_length=15),
        ),
    ]
